name: Release github

on:
  push:
    branches: [ main ]

jobs:

  release-github-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install FSharpPacker
      run: dotnet tool install --global FSharpPacker
    - name: Pack
      run: fspack converters/arc-convert-geo.fsx -o pkg -f net7.0
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.0.1"
        prerelease: false
        title: "v0.0.1"
        files: |
            pkg/arc-convert-geo.dll
